Repository DIT112-V20/group-04, pull requests merged in 2020-05, with the labels that each got.

#54 Voice control
  .idea/group-04.iml
  .travis.yml
  app/.travis.yml
  app/build.gradle
  app/src/androidTest/java/se/healthrover/CarSelectTest.java
  app/src/androidTest/java/se/healthrover/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/HttpService.java
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/ui_activity_controller/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/VoiceControl.java
  app/src/main/res/layout/guide_popup.xml
  app/src/main/res/layout/manual_control.xml
  app/src/main/res/layout/voice_control.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/se/healthrover/ExampleUnitTest.java
  app/src/test/java/se/healthrover/entities/CarCommandsTest.java
  app/src/test/java/se/healthrover/entities/HealthRoverTest.java
  arduino/obstacleAvoidance/basicObstacleAvoidance.ino
Labels: Sprint #3

#58 Android application user interface
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/VoiceControl.java
  app/src/main/res/drawable/button_mic.xml
  app/src/main/res/drawable/button_primary.xml
  app/src/main/res/drawable/ic_directions_car_white_24dp.xml
  app/src/main/res/drawable/ic_help_outline_white_24dp.xml
  app/src/main/res/drawable/ic_mic_none_white_small.xml
  app/src/main/res/drawable/ic_mic_white_24dp.xml
  app/src/main/res/drawable/ic_wifi_black_24dp.xml
  app/src/main/res/font/raleway.xml
  app/src/main/res/font/raleway_bold.xml
  app/src/main/res/font/raleway_semibold.xml
  app/src/main/res/layout/car_select.xml
  app/src/main/res/layout/guide_popup.xml
  app/src/main/res/layout/manual_control.xml
  app/src/main/res/layout/voice_control.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Sprint #4

#64 Speech recognition
  .gitignore
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/RequestTask.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/SpeechRecognition.java
  app/src/main/res/layout/speech_recognition.xml
  app/src/main/res/raw/dialogflow_access_key.json
Labels: Sprint #4

#66 Add module exclusions for DialogFlow's dependency
  app/build.gradle
Labels: Sprint #5, bug

#74 Extended speech recognition and refactoring
  README.md
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/SpeechRecognition.java
  app/src/main/res/values/strings.xml
Labels: Sprint #5

#75 Object factory
  app/src/androidTest/java/se/healthrover/ManualControlTest.java
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/OkHttpWebService.java
  app/src/main/java/se/healthrover/entities/HealthRoverCar.java
  app/src/main/java/se/healthrover/entities/ObjectFactory.java
  app/src/main/java/se/healthrover/ui_activity_controller/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/UserInterfaceUtilities.java
  app/src/main/java/se/healthrover/ui_activity_controller/error_handling/ActivityExceptionHandler.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/RequestTask.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/SpeechRecognition.java
  app/src/main/res/values/strings.xml
Labels: Sprint #5

#78 Feedback
  .travis.yml
  app/src/androidTest/java/se/healthrover/ResponseHandlerTestUI.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/OkHttpWebService.java
  app/src/main/java/se/healthrover/conectivity/ResponseHandler.java
  app/src/main/java/se/healthrover/entities/ObjectFactory.java
  app/src/main/res/values/strings.xml
Labels: Sprint #6

#82 Smartcar logic improvements
  app/src/main/java/se/healthrover/car_service/CarManagement.java
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/error_handling/ActivityExceptionHandler.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/SpeechRecognition.java
  app/src/test/java/se/healthrover/entities/CarManagementImpTest.java
  arduino/healthRover/healthRover.ino
Labels: Sprint #6, enhancement, highpriority

#94 Final changes to the project's documentation and bug-fixes
  .gitattributes
  README.md
  app/src/androidTest/java/se/healthrover/CarManagementTest.java
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/LocalNetworkDeviceNameResolver.java
  app/src/main/java/se/healthrover/ui_activity_controller/car_selection/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controller/voice_control/SpeechRecognition.java
  app/src/test/java/se/healthrover/entities/CarManagementImpTest.java
  app/src/test/java/se/healthrover/entities/CarTest.java
  app/src/test/java/se/healthrover/entities/TestCar.java
  misc/healthrover_yt_img.png
Labels: Sprint #7

#96 Update gitattributes
  .gitattributes
Labels: documentation

#95 Update ReadMe.md
  README.md
Labels: documentation
