Repository DIT112-V20/group-04, pull requests merged in 2020-04, with the labels that each got.

#7 Basic obstacle avoidance
  arduino/obstacleAvoidance/basicObstacleAvoidance.ino
Labels: Sprint #0

#20 Wifi Connectivity
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/group-04.iml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  app/.gitignore
  app/.travis.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/se/healthrover/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/car_service/CarManagement.java
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/HttpService.java
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/entities/HealthRoverCar.java
  app/src/main/java/se/healthrover/ui_activity_controler/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controler/ManualControl.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/car_select.xml
  app/src/main/res/layout/manual_control.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/se/healthrover/ExampleUnitTest.java
  arduino/healthRover/healthRover.ino
  arduino/obstacleAvoidance/basicObstacleAvoidance.ino
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Sprint #1

#32 Manual maneuvering
  .idea/group-04.iml
  .idea/modules.xml
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/car_service/CarManagement.java
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/HttpService.java
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/entities/HealthRoverCar.java
  app/src/main/java/se/healthrover/ui_activity_controler/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/res/drawable/joystick_background.png
  app/src/main/res/drawable/joystick_inner.png
  app/src/main/res/layout/car_select.xml
  app/src/main/res/layout/manual_control.xml
  app/src/main/res/values/strings.xml
  arduino/healthRover/healthRover.ino
Labels: Sprint #2

#34 Travic ci test
  app/src/test/java/se/healthrover/entities/HealthRoverTest.java
Labels: Sprint #3

#33 Implement navigation between manual and voice pages
  .idea/group-04.iml
  app/src/main/AndroidManifest.xml
  app/src/main/java/se/healthrover/ui_activity_controller/CarSelect.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
  app/src/main/java/se/healthrover/ui_activity_controller/VoiceControl.java
  app/src/main/res/layout/manual_control.xml
  app/src/main/res/layout/voice_control.xml
  app/src/main/res/values/strings.xml
Labels: Sprint #3

#38 Bug fixes maneuvering
  arduino/healthRover/healthRover.ino
Labels: Sprint #3

#40 Refactor voice control variables
  app/src/main/java/se/healthrover/entities/CarCommands.java
  app/src/main/java/se/healthrover/ui_activity_controller/VoiceControl.java
Labels: Sprint #3

#42 Voice control guide
  app/src/main/java/se/healthrover/ui_activity_controller/VoiceControl.java
  app/src/main/res/layout/guide_popup.xml
  app/src/main/res/layout/voice_control.xml
  app/src/main/res/values/strings.xml
Labels: Sprint #3

#46 Joystick fixes
  app/src/main/java/se/healthrover/car_service/CarManagementImp.java
  app/src/main/java/se/healthrover/conectivity/HttpService.java
  app/src/main/java/se/healthrover/ui_activity_controller/ManualControl.java
Labels: Sprint #3
